//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurshachCTO1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public int ApplicationNumber { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public int ClientId { get; set; }
        public int CarId { get; set; }
        public int ServiceId { get; set; }
        public int EmployeeId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> RequestStatusId { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Services Services { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual RequestStatus RequestStatus1 { get; set; }
    }
}
